### ISSUE TITLE
And the 4.0 version

### ISSUE THREAD

**Issue by carmas123** [roadhouse-dev/RxDbflow#1]
When you release it for the new DBFlow version?

**Comment by dwaynehoy** [comment]
Hey,

Unfortunately while dbflow 4 is in beta, developing against it is tough. Small changes from one beta to the next can break wrappers pretty quickly.

Saying that, I am working on support and the version below should support majority of the functionality and is tested against 4.0.0-beta5. 

'com.github.roadhouse-dev:RxDbflow:90ccf4b22b'

You can also try the latest dbflow4 snapshot
'com.github.roadhouse-dev:RxDbflow:feature~dbflow_4-SNAPSHOT'

If you have any issues let me know

**Comment by carmas123** [comment]
Thank you so much

**Comment by carmas123** [comment]
But you use RxJava2 or 1?

**Comment by dwaynehoy** [comment]
It's based on RxJava1, upgrading to RxJava2 is currently being worked on.

**Comment by dwaynehoy** [comment]
RxDbFlow 4 shapshot has been updated to RxJava2. I haven't had much time to perform solid testing yet, but everything inside the example app is working as expected.

`compile 'com.github.roadhouse-dev:RxDbflow:feature~dbflow_4-SNAPSHOT'`

**Comment by carmas123** [comment]
Ok, I test it for you :)

**Comment by dwaynehoy** [comment]
RxDbFlow now supports 4.0.0-Beta7, and RxJava1 and RxJava2
